packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  cli:
    '@antfu/eslint-config': ^4.8.1
    '@antfu/ni': ^23.3.1
    bumpp: ^10.0.3
    eslint: ^9.21.0
    lint-staged: ^15.4.3
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
    vite: ^6.2.1
  testing:
    '@types/js-yaml': ^4.0.9
    js-yaml: ^4.1.0
    vitest-package-exports: ^0.1.1
    vitest: ^3.0.8
  types:
    '@types/node': ^22.13.9
  utils:
    '@antfu/utils': ^9.1.0
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
