catalogMode: prefer
ignoreWorkspaceRootCheck: true
minimumReleaseAgeExclude:
  - '@types/node@25.9.0'
  - tsx@4.22.2
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  cli:
    '@antfu/eslint-config': ^9.0.0
    '@antfu/ni': ^30.1.0
    bumpp: ^11.1.0
    eslint: ^10.4.0
    nano-staged: ^1.0.2
    publint: ^0.3.21
    simple-git-hooks: ^2.13.1
    skills-npm: ^1.1.1
    tsdown: ^0.22.0
    tsx: ^4.22.2
    typescript: ^6.0.3
    vite: ^8.0.13
  inlined:
    '@antfu/utils': ^9.3.0
  testing:
    tsdown-stale-guard: ^0.1.2
    tsnapi: ^0.3.3
    vitest: ^4.1.6
  types:
    '@types/node': ^25.9.0
allowBuilds:
  esbuild: true
  simple-git-hooks: true
